version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:

services:

  db:
    image: postgres:13
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
      image: rv369/foodgram_backend:latest
      env_file: .env
      restart: always
      volumes:
        - static_value:/app/static/
        - media_value:/app/media/
      depends_on:
        - db


  frontend:
    image: rv369/foodgram_frontend:latest
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: rv369/foodgram_nginx:latest
    env_file: .env
    ports: 
      - "8008:80"
    volumes:
      # - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    restart: always
